// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnLvW4rUAkBxKNn72Tv7keMHajGqwLSak',
    appId: '1:376507505979:android:630fd5f516b5026f016b1e',
    messagingSenderId: '376507505979',
    projectId: 'note-app-fa76b',
    databaseURL: 'https://note-app-fa76b-default-rtdb.firebaseio.com',
    storageBucket: 'note-app-fa76b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYzbzEyUvU0kzKOGcfU8KxbvMU3EUXmLg',
    appId: '1:376507505979:web:a5577905517150fd016b1e',
    messagingSenderId: '376507505979',
    projectId: 'note-app-fa76b',
    authDomain: 'note-app-fa76b.firebaseapp.com',
    databaseURL: 'https://note-app-fa76b-default-rtdb.firebaseio.com',
    storageBucket: 'note-app-fa76b.firebasestorage.app',
    measurementId: 'G-CVBVEQSN4F',
  );
}
